### ISSUE TITLE
Move ui-core and possibly i18n to peer dependencies

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui-widgets#229]
This should be done for both ui-forms and ui-widgets. For ui-forms see https://github.com/dhis2/ui-forms/issues/141

**Comment by varl** [comment]
This has been done for ui-core: https://github.com/dhis2/ui-widgets/blob/master/package.json#L74

Still not sure about d2-i18n, will investigate.

**Comment by varl** [comment]
Related:
https://github.com/dhis2/ui-core/pull/660
https://github.com/dhis2/ui-widgets/pull/242
https://github.com/dhis2/ui-forms/pull/152

**Comment by varl** [comment]
All runtime dependencies that are provided by the app-platform should be marked as peer dependencies to avoid duplicates (e.g. ui-core, ui-widgets, styled-jsx, d2-i18n, 0prop-types).

**Comment by HendrikThePendric** [comment]
Update: https://github.com/dhis2/ui-forms/pull/152 was merged

**Comment by varl** [comment]
Ok, @HendrikThePendric. I made a change on `ui-core` yesterday to set `@dhis2/prop-types` as a runtime dep: https://github.com/dhis2/ui-core/pull/660#issuecomment-564517501 and only keep the singletons as peer deps. Been holding off on merging those while I have my thinking hat on.

**Comment by HendrikThePendric** [comment]
Oops... 
https://github.com/dhis2/ui-forms/pull/156 puts `@dhis2/prop-types` back to the dependencies

**Comment by varl** [comment]
I think we got'em all.
