### ISSUE TITLE
New component: item-selector

### ISSUE THREAD

**Issue by jenniferarnesen** [dhis2/ui-widgets#6]
Analytics team has an "item-selector" component that is currently used in the period and dimension selectors (not org-unit selector) in dashboard, data-vis and maps.

It supports:
* Moving items from one state to another
* Filtering the items on the left side
* Requesting more items when scroll-bottom is reached on the left side
* Sorting on the right side (by single or multi-dragging items)

I have seen similar functionality in the maintenance-app, though the gui is a little different. 

It has one dependency: react-beautiful-dnd

Here is what it looks like:

![image](https://user-images.githubusercontent.com/6113918/58084446-2f0d1c80-7bbb-11e9-8047-1366d04792e9.png)

What are people's thoughts on moving this to ui-widgets?  One reason I want to move it out of its current location (d2-ui-analytics) is because it is causing a weird dependency tree.

**Comment by varl** [comment]
> One reason I want to move it out of its current location (d2-ui-analytics) is because it is causing a weird dependency tree.

I would like some more information about this. I don't want to move a "weird dependency tree" from one place to another.

**Comment by jenniferarnesen** [comment]
A picture is worth a thousand words?

![dependencies](https://user-images.githubusercontent.com/6113918/58099093-3fcd8a80-7bdb-11e9-8fda-0fd5a9f70926.jpg)

**Comment by jenniferarnesen** [comment]
You can ask why we have a period-selector and a period-dimension, and why they are in different packages. That would be a good question. I don't have a complete answer, but as I understand, the period-selector is more generic than analytics, while the period dimension has additional features that make it specific to the analytics apps.

**Comment by varl** [comment]
```

        +-------------------------+
        |   d2-ui-analytics       |
        |-------------------------|
        |                         |
        | period-dimension        |
        | item-selector           |
        |                         |
        | period-selector-dialog  |
        |                         |
        +-------------------------+
```

Why cannot the period-selector-dialog live in the d2-ui-analytics package with the components it is built with?
